package com.example.p2paudio.model

enum class FailureCode {
    PERMISSION_DENIED,
    AUDIO_CAPTURE_NOT_SUPPORTED,
    WEBRTC_NEGOTIATION_FAILED,
    PEER_UNREACHABLE,
    NETWORK_CHANGED,
    USB_TETHER_UNAVAILABLE,
    USB_TETHER_DETECTED_BUT_NOT_REACHABLE,
    NETWORK_INTERFACE_NOT_USABLE,
    SESSION_EXPIRED,
    INVALID_PAYLOAD
}
